/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: ["./src/**/*.{js,jsx,ts,tsx}", "./public/index.html"],
  theme: {
    extend: {
      fontFamily: {
        display: ['"Cabinet Grotesk"', '"Manrope"', "system-ui", "sans-serif"],
        sans: ['"Manrope"', "system-ui", "sans-serif"],
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      colors: {
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        card: { DEFAULT: "hsl(var(--card))", foreground: "hsl(var(--card-foreground))" },
        popover: { DEFAULT: "hsl(var(--popover))", foreground: "hsl(var(--popover-foreground))" },
        primary: { DEFAULT: "hsl(var(--primary))", foreground: "hsl(var(--primary-foreground))" },
        secondary: { DEFAULT: "hsl(var(--secondary))", foreground: "hsl(var(--secondary-foreground))" },
        muted: { DEFAULT: "hsl(var(--muted))", foreground: "hsl(var(--muted-foreground))" },
        accent: { DEFAULT: "hsl(var(--accent))", foreground: "hsl(var(--accent-foreground))" },
        destructive: { DEFAULT: "hsl(var(--destructive))", foreground: "hsl(var(--destructive-foreground))" },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        aasha: {
          bg: "#FCFBF8",
          sidebar: "#F5F3ED",
          surface: "#FFFFFF",
          orange: "#F26C4F",
          orangeHover: "#E05A3D",
          orangeLight: "#F9E0D9",
          ink: "#2C2A29",
          inkSoft: "#7A7571",
          inkMuted: "#A39E98",
          line: "#E6E3DB",
          divider: "#F0EFEB",
          online: "#48B07D",
          tickRead: "#4A90E2",
        },
      },
      keyframes: {
        "accordion-down": { from: { height: "0" }, to: { height: "var(--radix-accordion-content-height)" } },
        "accordion-up": { from: { height: "var(--radix-accordion-content-height)" }, to: { height: "0" } },
        "bubble-in-right": { "0%": { opacity: "0", transform: "scale(0.7) translateY(8px)", transformOrigin: "bottom right" }, "100%": { opacity: "1", transform: "scale(1) translateY(0)" } },
        "bubble-in-left": { "0%": { opacity: "0", transform: "scale(0.7) translateY(8px)", transformOrigin: "bottom left" }, "100%": { opacity: "1", transform: "scale(1) translateY(0)" } },
        "slide-up": { "0%": { opacity: "0", transform: "translateY(10px)" }, "100%": { opacity: "1", transform: "translateY(0)" } },
        "pulse-dot": { "0%,100%": { opacity: "0.4" }, "50%": { opacity: "1" } },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "bubble-in-right": "bubble-in-right 0.25s cubic-bezier(0.34, 1.56, 0.64, 1)",
        "bubble-in-left": "bubble-in-left 0.25s cubic-bezier(0.34, 1.56, 0.64, 1)",
        "slide-up": "slide-up 0.3s ease-out",
        "pulse-dot": "pulse-dot 1.4s ease-in-out infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
